nama= input("siapa namamu?:")
sekolah= input("sekolah dimana?:")
kelas= input("kelas berapa sekarang?:")
jurusan= input ("masuk jurusan mana sekrang?:")
hobi= input("hobi kamu apa?:")
umur= input("umur kamu berapa?:")
makanan= input("suka makanan apa?:")
game= input("game favoritmu apa?:")
minuman= input("suka minuman apa?:")
motor= input("suka motor apa?:")
print ("halo, nama saya",nama , "saya bersekolah di",sekolah,"saya kelas",kelas,"dan saya masuk jurusan",jurusan,"hobi saya itu",hobi,"umur berapa",umur,"aku suka makanan",makanan,"aku suka game",game,"aku suka minuman",minuman,"aku suka motor",motor)